"""Add engine core tables

Revision ID: 186c72e410d9
Revises: ff435a32504f
Create Date: 2026-03-07 12:30:20.817240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186c72e410d9'
down_revision: Union[str, Sequence[str], None] = 'ff435a32504f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_report_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('active_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_report_definitions_tenant_id'), 'engine_report_definitions', ['tenant_id'], unique=False)
    op.create_table('engine_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_artifacts_dataset_version_id'), 'engine_artifacts', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_engine_artifacts_tenant_id'), 'engine_artifacts', ['tenant_id'], unique=False)
    op.create_table('engine_report_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['engine_report_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_report_versions_report_id'), 'engine_report_versions', ['report_id'], unique=False)
    op.create_table('engine_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=True),
    sa.Column('report_version_id', sa.String(length=36), nullable=True),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('error_truncated', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_version_id'], ['engine_report_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_runs_dataset_version_id'), 'engine_runs', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_engine_runs_tenant_id'), 'engine_runs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engine_runs_tenant_id'), table_name='engine_runs')
    op.drop_index(op.f('ix_engine_runs_dataset_version_id'), table_name='engine_runs')
    op.drop_table('engine_runs')
    op.drop_index(op.f('ix_engine_report_versions_report_id'), table_name='engine_report_versions')
    op.drop_table('engine_report_versions')
    op.drop_index(op.f('ix_engine_artifacts_tenant_id'), table_name='engine_artifacts')
    op.drop_index(op.f('ix_engine_artifacts_dataset_version_id'), table_name='engine_artifacts')
    op.drop_table('engine_artifacts')
    op.drop_index(op.f('ix_engine_report_definitions_tenant_id'), table_name='engine_report_definitions')
    op.drop_table('engine_report_definitions')
    # ### end Alembic commands ###
