"""profiles_tables

Revision ID: ff435a32504f
Revises: 0001
Create Date: 2026-03-06 12:08:25.065125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff435a32504f'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_tenant_id'), 'groups', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('csv_tab_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active_version', sa.Integer(), nullable=False),
    sa.Column('is_default_for_source', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_tab_profiles_owner_user_id'), 'csv_tab_profiles', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_csv_tab_profiles_source'), 'csv_tab_profiles', ['source'], unique=False)
    op.create_index(op.f('ix_csv_tab_profiles_tenant_id'), 'csv_tab_profiles', ['tenant_id'], unique=False)
    op.create_table('group_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_user_id'), 'group_memberships', ['user_id'], unique=False)
    op.create_table('csv_tab_profile_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['csv_tab_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_tab_profile_shares_group_id'), 'csv_tab_profile_shares', ['group_id'], unique=False)
    op.create_index(op.f('ix_csv_tab_profile_shares_profile_id'), 'csv_tab_profile_shares', ['profile_id'], unique=False)
    op.create_index(op.f('ix_csv_tab_profile_shares_user_id'), 'csv_tab_profile_shares', ['user_id'], unique=False)
    op.create_table('csv_tab_profile_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['csv_tab_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_tab_profile_versions_profile_id'), 'csv_tab_profile_versions', ['profile_id'], unique=False)
    op.drop_constraint(op.f('dataset_metrics_version_id_key'), 'dataset_metrics', type_='unique')
    op.add_column('dataset_versions', sa.Column('used_profile_ids', sa.Text(), nullable=True))
    op.drop_column('dataset_versions', 'profile_id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('dataset_versions', sa.Column('profile_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_column('dataset_versions', 'used_profile_ids')
    op.create_unique_constraint(op.f('dataset_metrics_version_id_key'), 'dataset_metrics', ['version_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_csv_tab_profile_versions_profile_id'), table_name='csv_tab_profile_versions')
    op.drop_table('csv_tab_profile_versions')
    op.drop_index(op.f('ix_csv_tab_profile_shares_user_id'), table_name='csv_tab_profile_shares')
    op.drop_index(op.f('ix_csv_tab_profile_shares_profile_id'), table_name='csv_tab_profile_shares')
    op.drop_index(op.f('ix_csv_tab_profile_shares_group_id'), table_name='csv_tab_profile_shares')
    op.drop_table('csv_tab_profile_shares')
    op.drop_index(op.f('ix_group_memberships_user_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_csv_tab_profiles_tenant_id'), table_name='csv_tab_profiles')
    op.drop_index(op.f('ix_csv_tab_profiles_source'), table_name='csv_tab_profiles')
    op.drop_index(op.f('ix_csv_tab_profiles_owner_user_id'), table_name='csv_tab_profiles')
    op.drop_table('csv_tab_profiles')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_groups_tenant_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
