"""Adapter module: re-export Engine ORM models from compliance_gate.Engine."""

from compliance_gate.Engine.models import (
    EngineArtifact,
    EngineClassificationDivergence,
    EngineClassificationMigration,
    EngineClassificationMode,
    EngineRuleBlock,
    EngineRuleEntry,
    EngineRuleSetDefinition,
    EngineRuleSetVersion,
    EngineReportDefinition,
    EngineReportVersion,
    EngineRun,
    EngineSegmentDefinition,
    EngineSegmentVersion,
    EngineTransformationDefinition,
    EngineTransformationVersion,
    EngineViewDefinition,
    EngineViewVersion,
)

__all__ = [
    "EngineArtifact",
    "EngineClassificationDivergence",
    "EngineClassificationMigration",
    "EngineClassificationMode",
    "EngineRuleBlock",
    "EngineRuleEntry",
    "EngineRuleSetDefinition",
    "EngineRuleSetVersion",
    "EngineSegmentDefinition",
    "EngineSegmentVersion",
    "EngineReportDefinition",
    "EngineReportVersion",
    "EngineRun",
    "EngineTransformationDefinition",
    "EngineTransformationVersion",
    "EngineViewDefinition",
    "EngineViewVersion",
]
